/*
 * Copyright 2020 HM Revenue & Customs
 *
 */

package utils

object SecureCommsMessageBodyStrings {
  val validEDODString: String = "<![CDATA[<P>TEMPLATE-ID|VRT41A_SM1A</P><P>VRN|100065579</P>" +
    "<P>FORM BUNDLE REFERENCE|092000003080</P><P>BUSINESS NAME|CoC Company Holdings Ltd</P>" +
    "<P>EFFECTIVE DATE OF DEREGISTRATION|20181227</P><P>TRANSACTOR EMAIL|Info_in_FB@CoCHoldingsLtd.co.uk</P>" +
    "<P>CUSTOMER EMAIL|info@CoCHoldings.co.uk</P>" +
    "<P>CUSTOMER EMAIL STATUS|VERIFIED</P><P>NOTIFICATION PREFERENCE|EMAIL</P><P>CHANNEL PREFERENCE|PAPER</P><P>LANGUAGE PREFERENCE|ENGLISH</P>" +
    "<P>FORMAT PREFERENCE|TEXT</P><P>TRANSACTOR NAME|Pack Mule</P>]]>"

  val validPPOBChangeString: String = "<![CDATA[<P>TEMPLATE-ID|VRT41A_SM1A</P><P>VRN|100065579</P>" +
    "<P>FORM BUNDLE REFERENCE|092000003080</P><P>BUSINESS NAME|CoC Company Holdings Ltd</P><P>TRANSACTOR EMAIL|lydia@carryburdens.tam</P>" +
    "<P>CUSTOMER EMAIL|dovahkin@riften.tam</P><P>CUSTOMER EMAIL STATUS|VERIFIED</P><P>NOTIFICATION PREFERENCE|EMAIL</P>" +
    "<P>CHANNEL PREFERENCE|PAPER</P><P>LANGUAGE PREFERENCE|ENGLISH</P><P>FORMAT PREFERENCE|TEXT</P><P>TRANSACTOR NAME|Pack Mule</P>" +
    "<P>ADDRESS LINE1|</P><P>ADDRESS LINE2|</P><P>ADDRESS LINE3|</P><P>ADDRESS LINE4|</P><P>ADDRESS LINE5|</P>" +
    "<P>POST CODE|</P><P>COUNTRY NAME|</P>]]>"

  val validBankAccountChangeString: String = "<![CDATA[<P>TEMPLATE-ID|VRT41A_SM1A</P><P>VRN|100065579</P>" +
    "<P>FORM BUNDLE REFERENCE|092000003080</P><P>BUSINESS NAME|CoC Company Holdings Ltd</P><P>TRANSACTOR EMAIL|Info_in_FB@CoCHoldingsLtd.co.uk</P>" +
    "<P>CUSTOMER EMAIL|info@CoCHoldings.co.uk</P><P>CUSTOMER EMAIL STATUS|VERIFIED</P><P>NOTIFICATION PREFERENCE|EMAIL</P>" +
    "<P>CHANNEL PREFERENCE|PAPER</P><P>LANGUAGE PREFERENCE|ENGLISH</P><P>FORMAT PREFERENCE|TEXT</P><P>TRANSACTOR NAME|DRAGON BORN</P>" +
    "<P>BANK ACCOUNT NAME|</P><P>BANK ACCOUNT NUMBER|</P><P>BANK SORT CODE|</P>]]>"

  val validStaggerChangeString: String = "<![CDATA[<P>TEMPLATE-ID|VRT41A_SM1A</P><P>VRN|100065579</P>" +
    "<P>FORM BUNDLE REFERENCE|092000003080</P><P>BUSINESS NAME|CoC Company Holdings Ltd</P><P>TRANSACTOR EMAIL|Info_in_FB@CoCHoldingsLtd.co.uk</P>" +
    "<P>CUSTOMER EMAIL|info@CoCHoldings.co.uk</P><P>CUSTOMER EMAIL STATUS|VERIFIED</P><P>NOTIFICATION PREFERENCE|EMAIL</P>" +
    "<P>CHANNEL PREFERENCE|PAPER</P><P>LANGUAGE PREFERENCE|ENGLISH</P><P>FORMAT PREFERENCE|TEXT</P><P>TRANSACTOR NAME|DRAGON BORN</P>" +
    "<P>STAGGER|</P>]]>"

  val validEmailChangeString: String = "<![CDATA[<P>TEMPLATE-ID|VRT41A_SM1A</P><P>VRN|100065579</P>" +
    "<P>FORM BUNDLE REFERENCE|092000003080</P><P>BUSINESS NAME|CoC Company Holdings Ltd</P><P>TRANSACTOR EMAIL|Info_in_FB@CoCHoldingsLtd.co.uk</P>" +
    "<P>CUSTOMER EMAIL|info@CoCHoldings.co.uk</P><P>CUSTOMER EMAIL STATUS|VERIFIED</P><P>NOTIFICATION PREFERENCE|EMAIL</P>" +
    "<P>CHANNEL PREFERENCE|PAPER</P><P>LANGUAGE PREFERENCE|ENGLISH</P><P>FORMAT PREFERENCE|TEXT</P><P>TRANSACTOR NAME|DRAGON BORN</P>" +
    "<P>ORIGINAL EMAIL ADDRESS|</P>]]>"

  val validBusinessNameChangeString: String = "<![CDATA[<P>TEMPLATE-ID|VRT41A_SM1A</P><P>VRN|100065579</P>" +
    "<P>FORM BUNDLE REFERENCE|092000003080</P><P>BUSINESS NAME|CoC Company Holdings Ltd</P><P>TRANSACTOR EMAIL|Info_in_FB@CoCHoldingsLtd.co.uk</P>" +
    "<P>CUSTOMER EMAIL|info@CoCHoldings.co.uk</P><P>CUSTOMER EMAIL STATUS|VERIFIED</P><P>NOTIFICATION PREFERENCE|EMAIL</P>" +
    "<P>CHANNEL PREFERENCE|PAPER</P><P>LANGUAGE PREFERENCE|ENGLISH</P><P>FORMAT PREFERENCE|TEXT</P><P>TRANSACTOR NAME|DRAGON BORN</P>]]>"

  val invalidEDODString: String = "<![CDATA[<P>TEMPLATE-ID|VRT41A_SM1A</P><P>VRN|100065579</P>" +
    "<P>FORM BUNDLE REFERENCE|092000003080</P><P>BUSINESS NAME|CoC Company Holdings Ltd</P>" +
    "<P>EFFECTIVE DATE OF DEREGISTRATION|20181227</P><P>TRANSACTOR EMAIL|Info_in_FB@CoCHoldingsLtd.co.uk</P>" +
    "<P>CUSTOMER EMAIL|info@CoCHoldings.co.uk</P>" +
    "<P>CUSTOMER EMAIL STATUS|VERIFIED</P><P>NOTIFICATION PREFERENCE|EMAIL</P><P>CHANNEL PREFERENCE|PAPER</P><P>LANGUAGE PREFERENCE|ENGLISH</P>]]>"

  val invalidJsonParseString: String = "<![CDATA[<P>TEMPLATE-ID|VRT41A_SM1A</P><P>VRN|100065579</P>" +
    "<P>FORM BUNDLE REFERENCE|092000003080</P><P>BUSINESS NAME|CoC Company Holdings Ltd</P>" +
    "<P>EFFECTIVE DATE OF DEREGISTRATION|20181227</P><P>TRANSACTOR EMAIL|Info_in_FB@CoCHoldingsLtd.co.uk</P>" +
    "<P>CUSTOMER EMAIL|info@CoCHoldings.co.uk</P>" +
    "<P>CUSTOMER EMAIL STATUS</P><P>NOTIFICATION PREFERENCE|EMAIL</P><P>CHANNEL PREFERENCE|PAPER</P><P>LANGUAGE PREFERENCE|ENGLISH</P>]]>"
}
